
development:
  adapter: mysql2
  encoding: utf8
  database: movie_development
  username: root
  password: square63

test:
  adapter: mysql2
  encoding: utf8
  database: movie_test
  username: root
  password: square63

production:
  adapter: mysql2
  encoding: utf8
  database: movie_production
  username: root
  password:
