
development:
  adapter: mysql2
  encoding: utf8
  database: movie_development
  username: root
  password: square63
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: movie_test
  username: root
  password: square63

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  username: sample_postgres
  password:
  database: movie_production
  # adapter: mysql2
  # database: movie_production
  # username: root
  # password:
  # encoding: utf8
